from os import getenv

from dotenv import load_dotenv

load_dotenv()

API_KEY = getenv("API_KEY")
API_SECRET_KEY = getenv("API_SECRET_KEY")
ACCESS_TOKEN = getenv("ACCESS_TOKEN")
ACCESS_TOKEN_SECRET = getenv("ACCESS_TOKEN_SECRET")
TWITTER_CREDENTIALS = (API_KEY, API_SECRET_KEY, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

WEBHOOK_URL = getenv("WEBHOOK_URL")
WATCH_LIST_ID = 1293148576634114049
