name: Deploy to VPS

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
            REMOTE_USER: ${{ secrets.DEPLOY_SERVER_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: /home/${{ secrets.DEPLOY_SERVER_USER }}/stream-tweet-in-list
      
      - name: Generate SSH key
        run: echo "$PKEY" > pkey && chmod 600 pkey
        env:
          PKEY: ${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}
        
      - name: Restart Docker Compose
        run: ssh $USER@$HOST -p $PORT -i pkey "cd /home/$USER/stream-tweet-in-list && docker-compose build --pull && docker-compose down -v && docker-compose up -d"
        env:
          HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          USER: ${{ secrets.DEPLOY_SERVER_USER }}
          PORT: ${{ secrets.REMOTE_PORT }}
